### ISSUE TITLE
Customer Data Import 

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#1123]
![Data-Import-Customer.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/a9675e2c-83a4-4a6c-b65a-f51088c2a907)
After click Upload – Code and Cname blank

**Comment by EiEiZin** [comment]
Code blank issue is due to some code is having special characters. we've fixed this issue.

Cname blank issue is due to naming case sensitive. the name should be as "CName". 
To prevent this issue, we updated the system to downlaod formatted template below.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/3c5ae5bf-f0d3-47a9-85f4-402e6f524ed1)
