### ISSUE TITLE
COA Data Import

### ISSUE THREAD

**Issue by A2000-ISTEAM** [a2000-erp-team/WEBERP#1126]
![2020-11-02_12h49_36.png](https://images.zenhubusercontent.com/5e8e8265b7c1d9906c2bbc2c/77f17e3f-4d7e-4c8b-8173-b9359d0da1a8)
After click Upload – All empty - Red Box
Map Field – Blue Box – should be the column name of the Excel

**Comment by EiEiZin** [comment]
The issue is due to template sheet name is wrong. it should be the name  - Sheet1.

![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/ec530018-9c96-48eb-88d4-a6ef7aa9ccaf)

we updated the system to download formatted template in screen below. 
![image.png](https://images.zenhubusercontent.com/5e21750e95a3326fc4d76dc2/cc5d3ee7-1e93-4b4b-a500-faf7e5218d33)
